# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
