# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160527_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='draft',
            new_name='published',
        ),
    ]
