# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160612_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[['Fiksi', 'Fiksi'], ['Berita', 'Berita'], ['Olahraga', 'Olahraga'], ['Teknologi', 'Teknologi']], max_length=50),
        ),
    ]
